# Generated by Django 5.1.2 on 2024-10-17 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
                ('cedula', models.CharField(max_length=20)),
                ('formula_medica', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo_producto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=30)),
                ('contrasena', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='cliente_producto',
            fields=[
                ('id_cliente_producto', models.AutoField(primary_key=True, serialize=False)),
                ('total_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OptiGest.cliente')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OptiGest.producto')),
            ],
        ),
        migrations.CreateModel(
            name='proveedor_producto',
            fields=[
                ('id_proveedor_producto', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OptiGest.producto')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OptiGest.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='cliente_usuario',
            fields=[
                ('id_usuario_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OptiGest.cliente')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OptiGest.usuario')),
            ],
        ),
    ]
