# Generated by Django 5.1.2 on 2024-11-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OptiGest', '0002_alter_cliente_cedula_alter_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='clienteForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('formula_medica', models.TextField()),
            ],
        ),
    ]
