# Generated by Django 5.1.2 on 2024-11-13 14:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OptiGest', '0003_clienteform'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteform',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
